import type { Listing } from '../types/listing.types';

export const CATEGORIES = [
  { id: 'all', title: 'Все', icon: 'grid-outline', type: 'quantity' },
  { id: 'dresses', title: 'Платья', icon: 'woman-outline', type: 'size' },
  { id: 'suits', title: 'Костюмы', icon: 'man-outline', type: 'size' },
  { id: 'furniture', title: 'Мебель', icon: 'bed-outline', type: 'quantity' },
  { id: 'dishes', title: 'Посуда', icon: 'restaurant-outline', type: 'quantity' },
  { id: 'decor', title: 'Декор', icon: 'flower-outline', type: 'quantity' },
  { id: 'tools', title: 'Инструменты', icon: 'construct-outline', type: 'quantity' },
  { id: 'kids', title: 'Детское', icon: 'balloon-outline', type: 'quantity' },
  { id: 'tents', title: 'Шатры', icon: 'home-outline', type: 'quantity' },
  { id: 'electronics', title: 'Техника', icon: 'camera-outline', type: 'quantity' },
];

export const ITEMS: Listing[] = [
  {
    id: '1',
    title: 'Свадебное платье "Grace"',
    price: '500 000 сум',
    priceNum: 500000,
    deposit: '1 000 000 сум',
    depositNum: 1000000,
    category: 'dresses',
    categoryType: 'size',
    location: 'Ташкент, Чиланзар',
    address: 'Ташкент, Чиланзар, 12-й квартал',
    latitude: 41.2856,
    longitude: 69.2035,
    image: require('../assets/images/dress1.png'),
    images: [
      require('../assets/images/dress1.png'),
      require('../assets/images/dress2.png'),
      require('../assets/images/dress3.png'),
    ],
    description: 'Изысканное платье из нежного кружева с длинным шлейфом. Состояние идеальное.',
    tags: ['свадьба', 'премиум', 'кружево', 'примерка'],
    characteristics: [
      { label: 'Состояние', value: 'Идеальное' },
      { label: 'Материал', value: 'Кружево, фатин' },
      { label: 'Цвет', value: 'Айвори' },
      { label: 'Длина шлейфа', value: '1.5 м' },
    ],
    seller: {
      id: 'user_alice',
      name: 'Алина',
      role: 'Прокат свадебных платьев',
      isVerified: true,
      phone: '+998 90 999 88 77',
      district: 'Чиланзарский район',
      address: 'Ташкент, Чиланзар, 12-й квартал, дом 18',
      latitude: 41.2856,
      longitude: 69.2035,
      workingHours: '10:00-20:00',
    },
    availableSizes: ['S', 'M', 'L', '42', '44', '46'],
    minRentalDays: 1,
    moderationStatus: 'approved',
    rating: 4.8,
    reviewCount: 12,
    blockedDates: ['2026-04-12', '2026-04-13', '2026-04-20'],
  },
  {
    id: '2',
    title: 'Набор стульев (100 шт)',
    price: '5 000 сум',
    priceNum: 5000,
    deposit: '300 000 сум',
    depositNum: 300000,
    category: 'furniture',
    categoryType: 'quantity',
    location: 'Ташкент, Юнусабад',
    address: 'Ташкент, Юнусабад, массив 4',
    latitude: 41.3688,
    longitude: 69.2898,
    image: require('../assets/images/dress2.png'),
    images: [
      require('../assets/images/dress2.png'),
      require('../assets/images/dress1.png'),
      require('../assets/images/dress3.png'),
    ],
    description: 'Стулья в стиле Tiffany, идеально подходят для выездных регистраций.',
    tags: ['мероприятие', 'мебель', 'доставка', 'опт'],
    characteristics: [
      { label: 'Материал', value: 'Металл, пластик' },
      { label: 'Цвет', value: 'Белый' },
      { label: 'Доступно', value: 'До 200 шт.' },
      { label: 'Минимум', value: '20 шт.' },
    ],
    seller: {
      id: 'user_bob',
      name: 'Бобур',
      role: 'Аренда мебели',
      isVerified: true,
      phone: '+998 90 555 44 33',
      district: 'Юнусабадский район',
      address: 'Ташкент, Юнусабад, массив 4, склад 2',
      latitude: 41.3688,
      longitude: 69.2898,
      workingHours: '09:00-19:00',
    },
    maxQuantity: 200,
    unit: 'шт',
    minRentalDays: 1,
    moderationStatus: 'approved',
    rating: 4.5,
    reviewCount: 8,
    blockedDates: ['2026-04-15', '2026-04-16'],
  },
  {
    id: '3',
    title: 'Хрустальные бокалы',
    price: '25 000 сум',
    priceNum: 25000,
    deposit: '150 000 сум',
    depositNum: 150000,
    category: 'dishes',
    categoryType: 'quantity',
    location: 'Ташкент, Чиланзар',
    address: 'Ташкент, Чиланзар, 12-й квартал',
    latitude: 41.2856,
    longitude: 69.2035,
    image: require('../assets/images/dress3.png'),
    images: [
      require('../assets/images/dress3.png'),
      require('../assets/images/dress1.png'),
    ],
    description: 'Набор из 50 хрустальных бокалов для шампанского.',
    tags: ['посуда', 'банкет', 'хрусталь'],
    characteristics: [
      { label: 'Комплект', value: '50 бокалов' },
      { label: 'Объем', value: '180 мл' },
      { label: 'Состояние', value: 'Без сколов' },
    ],
    seller: {
      id: 'user_alice',
      name: 'Алина',
      role: 'Прокат свадебных платьев',
      isVerified: true,
      phone: '+998 90 999 88 77',
      district: 'Чиланзарский район',
      address: 'Ташкент, Чиланзар, 12-й квартал, дом 18',
      latitude: 41.2856,
      longitude: 69.2035,
      workingHours: '10:00-20:00',
    },
    maxQuantity: 200,
    unit: 'шт',
    minRentalDays: 1,
    moderationStatus: 'approved',
    rating: 4.9,
    reviewCount: 15,
  },
  {
    id: '4',
    title: 'Арка для фотозоны',
    price: '150 000 сум',
    priceNum: 150000,
    deposit: '500 000 сум',
    depositNum: 500000,
    category: 'decor',
    categoryType: 'quantity',
    location: 'Ташкент, Чиланзар',
    address: 'Ташкент, Чиланзар, 12-й квартал',
    latitude: 41.2856,
    longitude: 69.2035,
    image: require('../assets/images/dress1.png'),
    images: [
      require('../assets/images/dress1.png'),
      require('../assets/images/dress3.png'),
    ],
    description: 'Кованая арка, украшенная искусственными цветами премиум качества.',
    tags: ['фотозона', 'декор', 'свадьба'],
    characteristics: [
      { label: 'Размер', value: '2.2 x 2.4 м' },
      { label: 'Монтаж', value: '30 минут' },
      { label: 'Материал', value: 'Металл, искусственные цветы' },
    ],
    seller: {
      id: 'user_alice',
      name: 'Алина',
      role: 'Прокат свадебных платьев',
      isVerified: true,
      phone: '+998 90 999 88 77',
      district: 'Чиланзарский район',
      address: 'Ташкент, Чиланзар, 12-й квартал, дом 18',
      latitude: 41.2856,
      longitude: 69.2035,
      workingHours: '10:00-20:00',
    },
    maxQuantity: 50,
    unit: 'шт',
    minRentalDays: 1,
    moderationStatus: 'approved',
    rating: 4.7,
    reviewCount: 6,
  },
];
