export const CATEGORIES = [
  { id: 'all', title: 'Все', icon: 'grid-outline', type: 'quantity' },
  { id: 'dresses', title: 'Платья', icon: 'woman-outline', type: 'size' },
  { id: 'suits', title: 'Костюмы', icon: 'man-outline', type: 'size' },
  { id: 'furniture', title: 'Мебель', icon: 'bed-outline', type: 'quantity' },
  { id: 'dishes', title: 'Посуда', icon: 'restaurant-outline', type: 'quantity' },
  { id: 'decor', title: 'Декор', icon: 'flower-outline', type: 'quantity' },
  { id: 'tools', title: 'Инструменты', icon: 'construct-outline', type: 'quantity' },
  { id: 'kids', title: 'Детское', icon: 'balloon-outline', type: 'quantity' },
  { id: 'tents', title: 'Шатры', icon: 'home-outline', type: 'quantity' },
  { id: 'electronics', title: 'Техника', icon: 'camera-outline', type: 'quantity' },
];

export const ITEMS = [
  {
    id: '1',
    title: 'Свадебное платье "Grace"',
    price: '500 000 сум',
    priceNum: 500000,
    category: 'dresses',
    categoryType: 'size',
    location: 'Ташкент',
    image: require('../assets/images/dress1.png'),
    description: 'Изысканное платье из нежного кружева с длинным шлейфом. Состояние идеальное.',
    seller: { id: 'user_alice', name: 'Алина', role: 'Прокат свадебных платьев' },
    availableSizes: ['S', 'M', 'L', '42', '44', '46'],
    rating: 4.8,
    reviewCount: 12,
    blockedDates: ['2026-04-12', '2026-04-13', '2026-04-20'],
  },
  {
    id: '2',
    title: 'Набор стульев (100 шт)',
    price: '5 000 сум',
    priceNum: 5000,
    category: 'furniture',
    categoryType: 'quantity',
    location: 'Ташкент',
    image: require('../assets/images/dress2.png'),
    description: 'Стулья в стиле Tiffany, идеально подходят для выездных регистраций.',
    seller: { id: 'user_bob', name: 'Бобур', role: 'Аренда мебели' },
    maxQuantity: 200,
    unit: 'шт',
    rating: 4.5,
    reviewCount: 8,
    blockedDates: ['2026-04-15', '2026-04-16'],
  },
  {
    id: '3',
    title: 'Хрустальные бокалы',
    price: '25 000 сум',
    priceNum: 25000,
    category: 'dishes',
    categoryType: 'quantity',
    location: 'Ташкент',
    image: require('../assets/images/dress3.png'),
    description: 'Набор из 50 хрустальных бокалов для шампанского.',
    seller: { id: 'user_alice', name: 'Алина', role: 'Прокат свадебных платьев' },
    maxQuantity: 200,
    unit: 'шт',
    rating: 4.9,
    reviewCount: 15,
  },
  {
    id: '4',
    title: 'Арка для фотозоны',
    price: '150 000 сум',
    priceNum: 150000,
    category: 'decor',
    categoryType: 'quantity',
    location: 'Ташкент',
    image: require('../assets/images/dress1.png'),
    description: 'Кованая арка, украшенная искусственными цветами премиум качества.',
    seller: { id: 'user_alice', name: 'Алина', role: 'Прокат свадебных платьев' },
    maxQuantity: 50,
    unit: 'шт',
    rating: 4.7,
    reviewCount: 6,
  },
];